repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        additional_dependencies:
          - tomli
        args:
          - --check
          - --config
          - ./pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - requests[socks]
          - tzlocal
          - types-dateparser
          - types-python-dateutil
          - types-requests
          - types-urllib3
        args:
          - --config-file=pyproject.toml
