[project]
name = "eazyrest"
description = "Building blocks for easy REST API consumption"
authors = [
    {name = "Geoffrey Mainland", email = "mainland@apeiron.net"},
]
version = "0.1"
requires-python = ">=3.8"
dependencies = [
    "certifi",
    "dateparser",
    "isodate",
    "python-dateutil",
    "pytimeparse2",
    "requests[socks]",
    "tzlocal"
]

[project.optional-dependencies]
dev = [
  "types-dateparser",
  "types-python-dateutil",
  "types-requests",
  "types-urllib3"
]

[tool.setuptools.packages.find]
where = ["src"]
