[metadata]
name = eazyrest
version = 0.1
description = Building blocks for easy REST API consumption
author = Geoffrey Mainland
author_email = mainland@drexel.edu

[options]
packages = find_namespace:
include_package_data = true
python_requires = >=3.8
install_requires =
  certifi
  requests[socks]
